<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 2.1.1 
# *Data Wrangling and Munging with Pandas*

## Part 1: Wrangling Data

The term "data wrangling" is analogous to capturing wild horses and getting them into a fenced area; the horses are data and the fencing is your computer. The more common data wrangling tasks include:

- reading flat files
- reading Excel files
- downloading from web pages
  - csv
  - html
  - json

In [2]:
import numpy as np
import pandas as pd

*It is good practice to display the library version numbers for future reference:*

In [3]:
print('Numpy: ', np.__version__)
print('Pandas: ', pd.__version__)

Numpy:  1.23.5
Pandas:  1.5.3

### CSV Files

Below are three attempts to load the file "bikeshare.csv" into a DataFrame named `bikes`. Why are they wrong?

In [3]:
# wrong:
bikes = pd.read_table('bikeshare.csv', header = None)
print(bikes.head())           # It should be read_csv file and also path to be assigned
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 1)
print(bikes.head())
print()

# wrong:
bikes = pd.read_table('bikeshare.csv', header = 0)
print(bikes.head())

FileNotFoundError: [Errno 2] No such file or directory: 'bikeshare.csv'

ANSWER:

Load the file "bikeshare.csv" into a DataFrame named `bikes`, and confirm that it was loaded properly:

In [2]:
#ANSWER:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

bikes_csv=r'C:\Users\preej\IOD\Workspace\Module 2 --- Week2\bikeshare.csv'
bikes=pd.read_csv(bikes_csv)
bikes

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

Note that we could have used `read.csv()` above. When is `read_table()` necessary?

?:
ANSWER: When `sep` is not the comma character, or we need fine control that `read.csv()` does not provide.

Flat files can be full of surprises. Here are some issues to watch out for:

- separator character is something other than the comma
  - ";", "|", and tab are popular
- newline character is something other than what the O/S expects 
  - Tip: Don't hard-code the character codes for carriage returns, linefeeds, etc. Use Python's built-in representation instead (e.g. Python translates "\n" to the newline character and "\t" to the tab character on any O/S).
- truncated lines
  - if there are empty fields at the end of a line it is possible that their separators will be missing, resulting in a "jagged" file
- embedded commas or quotes
  - a free-text field containing embedded commas may split into separate fields on input
  - a free-text field containing embedded quotes may not parse correctly
- unescaped characters
  - the "\" character indicates a control code to Python, which will break the I/O
    - e.g. the substring "\u0123" will be interpreted as Unicode(0123) -- which may not be what the file creator intended
  - these may need to be fixed by loading whole strings and then parsing into a new data frame
  
Tip: Most issues can be delth with by correctly specifying the parameters of the function you use to load the file. Read the doco before reading the data!

### Reading Excel Files

In [1]:
from pandas import ExcelFile  # Nb. Need to install xlrd from conda (it does not automatically install with pandas)

In [4]:
#conda install -c conda-forge xlrd should run in anaconda prompt
df = pd.read_excel(r'C:\Users\preej\IOD\Workspace\Module 2 --- Week2\DATA/Iris.xls', sheet_name = 'Data')
df

,Species_No,Petal_width,Petal_length,Sepal_width,Sepal_length,Species_name
0,1,0.2,1.4,3.5,5.1,Setosa
1,1,0.2,1.4,3.0,4.9,Setosa
2,1,0.2,1.3,3.2,4.7,Setosa
3,1,0.2,1.5,3.1,4.6,Setosa
4,1,0.2,1.4,3.6,5.0,Setosa
...,...,...,...,...,...,...
145,3,2.3,5.2,3.0,6.7,Verginica
146,3,1.9,5.0,2.5,6.3,Verginica
147,3,2.0,5.2,3.0,6.5,Verginica
148,3,2.3,5.4,3.4,6.2,Verginica
149,3,1.8,5.1,3.0,5.9,Verginica

So, this file appears to have an embedded table of aggregates on the same sheet as the raw data (a naughty but common practice amongst analysts).

It is usually better to load data correctly than to meddle with the source file or load it 'warts and all' and then try to parse it in code. The Pandas functions for reading files have parameters that provide the control we need. For ecxample, we could make multiple calls to `read_excel()`, using combinations of the `header`, `usecols`, `skiprows`, `nrows`, and `skipfooter` parameters to load one table at a time from a spreadsheet with multiple tables.

Load the above file without the unwanted columns:

In [13]:
#conda install -c conda-forge xlrd
df = pd.read_excel(r'C:\Users\preej\IOD\Workspace\Module 2 --- Week2\DATA/Iris.xls', sheet_name = 'Data',header=0, usecols=[0,1,2])
df

     Species_No  Petal_width  Petal_length
0             1          0.2           1.4
1             1          0.2           1.4
2             1          0.2           1.3
3             1          0.2           1.5
4             1          0.2           1.4
..          ...          ...           ...
145           3          2.3           5.2
146           3          1.9           5.0
147           3          2.0           5.2
148           3          2.3           5.4
149           3          1.8           5.1

[150 rows x 3 columns]

### Importing Data Directly from the Web

We usually want to store a local copy of a data file that we download from the Web, but when data retention is not a priority it is convenient to download the data directly into our running Python environment.

#### Importing Text Files from the Web

The web is the 'wild west' of data formats. However, we can usually expect good behaviour from files that are automatically generated by a service, such as the earthquake report:

In [4]:
df = pd.read_csv('https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_hour.csv')
df.head()

,time,latitude,longitude,depth,mag,magType,nst,gap,dmin,rms,...,updated,place,type,horizontalError,depthError,magError,magNst,status,locationSource,magSource
0,2023-07-26T02:57:50.880Z,19.0035,-65.070667,15.38,3.35,md,9,284,0.6566,0.31,...,2023-07-26T03:07:28.480Z,"74 km NNW of Charlotte Amalie, U.S. Virgin Isl...",earthquake,4.51,8.88,0.108537,7,reviewed,pr,pr

#### Importing HTML Files from the Web

Working with unstructured HTML files relies heavily on library functions. This one, however, is well-structured:

In [5]:
url = 'https://www.ccra.com/airport-codes/'

df = pd.read_html(url)
df

[                City      Country Code
 0            Aalborg      Denmark  AAL
 1           Aalesund       Norway  AES
 2             Aarhus      Denmark  AAR
 3     Abbotsford, BC       Canada  YXX
 4     Abbotsford, BC       Canada  YXX
 ...              ...          ...  ...
 1574        Zanzibar     Tanzania  ZNZ
 1575        Zaragoza        Spain  ZAZ
 1576       Zhengzhou        China  CGO
 1577        Zhoushan        China  HSN
 1578          Zurich  Switzerland  ZRH

 [1579 rows x 3 columns]]

In [6]:
df[0]

                City      Country Code
0            Aalborg      Denmark  AAL
1           Aalesund       Norway  AES
2             Aarhus      Denmark  AAR
3     Abbotsford, BC       Canada  YXX
4     Abbotsford, BC       Canada  YXX
...              ...          ...  ...
1574        Zanzibar     Tanzania  ZNZ
1575        Zaragoza        Spain  ZAZ
1576       Zhengzhou        China  CGO
1577        Zhoushan        China  HSN
1578          Zurich  Switzerland  ZRH

[1579 rows x 3 columns]

#### Importing XML Files from the Web

XML files are semi-structured, but you're at the mercy of the file creator. If every record has the same format it will be much easier, but practical applications often require a lot of custom code. Here is an example that includes a nice parser class: http://www.austintaylor.io/lxml/python/pandas/xml/dataframe/2016/07/08/convert-xml-to-pandas-dataframe/

#### Importing JSON Files from the Web

Like XML, JSON files are semi-structured and may require work to capture the schema into a dataframe. Here is a simple example:

In [9]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/data.json'

# Load the first sheet of the JSON file into a data frame
df = pd.read_json(url, orient = 'columns')
df.head()

   integer            datetime  category
0        5 2015-01-01 00:00:00         0
1        5 2015-01-01 00:00:01         0
2        9 2015-01-01 00:00:02         0
3        6 2015-01-01 00:00:03         0
4        6 2015-01-01 00:00:04         0

## Part 2: Data Munging

Data munging is manipulating data to get it into a form that we can start running analyses on (which usually means getting the data into a DataFrame). Before we get to this stage, we may need to remove headers or footers, transpose columns to rows, split wide data tables into long ones, and so on. (Nb. Excel files can be particularly troublesome, because users can format their data in mixed, complex shapes.) Essentially, we need to follow Hadley Wickham's guidelines for tidy datasets (http://vita.had.co.nz/papers/tidy-data.html):

The end goal of the cleaning data process:

- each variable should be in one column
- each observation should comprise one row
- each type of observational unit should form one table
- include key columns for linking multiple tables
- the top row contains (sensible) variable names
- in general, save data as one file per table

### Dataset Morphology

Once we have our dataset in a DataFrame (or Series, if our data is only 1-dimensional), we can start examining its size and content.

How many rows and columns are in `bikes`?

In [3]:
#ANSWER
bikes.info()
#17379 rows × 17 columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

What are the column names in `bikes`?

In [8]:
#ANSWER
df = pd.DataFrame(bikes)

# Printing the column names
print(df.columns.tolist())

['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday', 'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed', 'casual', 'registered', 'cnt']

What are the data types of these columns?

In [24]:
#ANSWER
print(df.dtypes)

instant         int64
dteday         object
season          int64
yr              int64
mnth            int64
hr              int64
holiday         int64
weekday         int64
workingday      int64
weathersit      int64
temp          float64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

What is the (row) index for this DataFrame?

In [25]:
#ANSWER
print(df.index)

RangeIndex(start=0, stop=17379, step=1)

https://www.dataquest.io/blog/python-json-tutorial/

## Slicing and Dicing

It is often preferable to refer to DataFrame columns by name, but there is more than one way to do this. 
Do `bikes['season']` and `bikes[['season']]` give the same object? Demonstrate:

In [31]:
#ANSWER
bikes['season']
bikes[['season']]
#bikes['season'] gives you a Series.
#bikes[['season']] gives you a DataFrame with a single column.

       season
0           1
1           1
2           1
3           1
4           1
...       ...
17374       1
17375       1
17376       1
17377       1
17378       1

[17379 rows x 1 columns]

How would we use object notation to show the first 4 rows of `atemp`?

In [35]:
#ANSWER
df['atemp'].head(4)

0    0.2879
1    0.2727
2    0.2727
3    0.2879
Name: atemp, dtype: float64

Algorithms that loop over multiple columns often access DataFrame columns by index. However, none of the following work (try them out by uncommenting / removing the "#E: " ):

In [136]:
bikes[[0]]
#bikes[0]
# bikes[0,0]
# bikes[[0,0]]

KeyError: "None of [Int64Index([0], dtype='int64')] are in the [columns]"

What is the correct way to access the 1st row of the DataFrame by its index?

In [139]:
#ANSWER
#df
bikes.iloc[[1]]

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.8,0.0,8,32,40

In [138]:
bikes[1: 1]

Empty DataFrame
Columns: [instant, dteday, season, yr, mnth, hr, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed, casual, registered, cnt]
Index: []

What is the correct way to access the 2nd column of the DataFrame by its index?

In [140]:
#ANSWER
bikes.iloc[:,2]

0        1
1        1
2        1
3        1
4        1
        ..
17374    1
17375    1
17376    1
17377    1
17378    1
Name: season, Length: 17379, dtype: int64

## Handling Missing Values

What is the Pandas `isnull` function for?

?
ANSWER:

We can apply `isnull` to the `bikes` DataFrame to show the result for every element:

In [12]:
bikes.isnull().head()
# The isnull() function in Pandas is used to check for missing or null values in a DataFrame or a Series
 # The output DataFrame or Series will have True for null values and False for non-null values.

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

However, we usually start at a higher level. How many nulls are in `bikes` altogether?

In [16]:
#ANSWER
df.isnull().sum()
# the total count of null values across all columns
#df.isnull().sum().sum()

Species_No      0
Petal_width     0
Petal_length    0
Sepal_width     0
Sepal_length    0
Species_name    0
dtype: int64

If this result were nonzero we would next want to find out which columns contained nulls. How can this be done in one line of code?

In [37]:
#ANSWER
bikes.isnull().any()

instant       False
dteday        False
season        False
yr            False
mnth          False
hr            False
holiday       False
weekday       False
workingday    False
weathersit    False
temp          False
atemp         False
hum           False
windspeed     False
casual        False
registered    False
cnt           False
dtype: bool

What is the Numpy object `nan` used for? (Write a descriptive answer.)


ANSWER: 
In NumPy, nan stands for "Not a Number," and it is a special floating-point value used to represent missing or undefined data. It is a way to represent invalid or unrepresentable numerical values when working with numerical arrays in NumPy.

nan is often used to fill in missing values or indicate the result of an undefined or invalid mathematical operation. For example, when performing arithmetic operations involving undefined or invalid values (e.g., 0/0 or sqrt(-1)), NumPy will produce nan as the result.

Write (and verify) a function that performs scalar division with built-in handling of the edge case (i.e. return a value instead of just trapping the error):

In [10]:
#ANSWER
scalar1=50.755
scalar2= 5

scalar= scalar1 // scalar2

print(scalar)

10.0

In [11]:
def safe_divide(numerator, divisor, default_value=None):
    if divisor == 0:
        return default_value
    
    result = numerator / divisor
    return result

# Test cases
print(safe_divide(10, 2))   # Output: 5.0
print(safe_divide(5, 0))    # Output: None
print(safe_divide(0, 3))    # Output: 0.0
print(safe_divide(8, 2, -1))  # Output: 4.0
print(safe_divide(15, 0, -1))  # Output: -1

5.0
None
0.0
4.0
-1

Apply the Pandas `isna` function to the following data objects:

In [2]:
import numpy as np
x = 2.3
y = np.nan
print(x, y)

2.3 nan

In [145]:
#ANSWER
pd.isna(x)

False

In [29]:
array1 = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print(array1)

[[ 1. nan  3.]
 [ 4.  5. nan]]

In [149]:
#ANSWER
import pandas as pd
array1 = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print (array1)

print (pd.isna(array1))

# print(z)

[[ 1. nan  3.]
 [ 4.  5. nan]]
[[False  True False]
 [False False  True]]

How is the pandas I/O parameter `na_values` used?

ANSWER

By using the na_values parameter appropriately, you can ensure that pandas correctly identifies the missing data in your dataset and handles it accordingly during the data loading process.

## Data Profiling

### Counts

When there are categorical variables in a dataset we will want to know how many possible values there are in each column. (Nb. If the dataset is a sample of a larger one, our sample may not capture all possible values of every categorical.)

How many (different) seasons are in `bikes`?

In [5]:
#ANSWER

bikes.count()

instant       17379
dteday        17379
season        17379
yr            17379
mnth          17379
hr            17379
holiday       17379
weekday       17379
workingday    17379
weathersit    17379
temp          17379
atemp         17379
hum           17379
windspeed     17379
casual        17379
registered    17379
cnt           17379
dtype: int64

In [6]:
bikes

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

### Ranges

Print the range of the `instant`, `dteday`, and `windspeed` columns:

In [8]:
bikes["dteday"]=pd.to_datetime(bikes["dteday"])
bikes

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

In [9]:
#ANSWER
instant_range = bikes["instant"].max() - bikes["instant"].min()
print(instant_range)
dteday_range = bikes["dteday"].max() - bikes["dteday"].min()
print(dteday_range)
windspeed_range = bikes["windspeed"].max() - bikes["windspeed"].min()
print(windspeed_range)

17378
730 days 00:00:00
0.8507

Compute and print the overall minimum and maximum of the numeric data columns:

In [24]:
bikes_min, bikes_max = (
    min(bikes.min(numeric_only=True)), 
    max(bikes.max(numeric_only=True))
)
print(bikes_min, bikes_max)

0.0 17379.0

### Quantiles

Pandas makes computing quantiles easy. This is how to get the median of a Series:

In [ ]:
bikes['atemp'].quantile(0.5)

Of course, the `quantiles` method can take a tuple as its argument. Compute the 10th, 25th, 50th, 75th, and 90th percentiles in one line of code:

In [ ]:
#ANSWER
bikes['atemp'].quantile([0.5,0.25,0.50,0.75,0.90])

### Cuts

Sometimes we want to split the sample not by the quantiles of the distribution but by the range of the data. Let's take a closer look at `atemp`:

In [25]:
type(bikes['atemp'])

pandas.core.series.Series

In [4]:
bikes.sample(5)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
14862,14863,2012-09-16,3,1,9,11,0,0,0,1,0.64,0.6212,0.47,0.1642,183,376,559
398,399,2011-01-18,1,0,1,14,0,2,1,2,0.22,0.2273,0.80,0.1642,2,26,28
13942,13943,2012-08-09,3,1,8,3,0,4,1,1,0.68,0.6364,0.83,0.0896,1,5,6
14034,14035,2012-08-12,3,1,8,23,0,0,0,1,0.68,0.6364,0.61,0.0000,25,85,110
16384,16385,2012-11-20,4,1,11,10,0,2,1,2,0.40,0.4091,0.66,0.0896,32,144,176

Suppose we decide to sort these values into 4 bins of equal width, but we want to apply the resulting groups to the entire DataFrame. Basically, we need to add a row label that indcates which bin each sample belongs in. Let's call this label "atemp_level", and use the `cut` method to populate it:

In [ ]:
atemp_level = pd.cut(bikes['atemp'], bins = 4)       
atemp_level

What is `atemp_level`?

In [ ]:
#ANSWER
atemp_level is the one of the column feature of the bikes data set.

Here is a random sample of `atemp_level`:

In [10]:
atemp_level.sample(5)

3741     (0.5, 0.75]
7542     (0.25, 0.5]
5724     (0.5, 0.75]
13261    (0.5, 0.75]
16251    (0.25, 0.5]
Name: atemp, dtype: category
Categories (4, interval[float64, right]): [(-0.001, 0.25] < (0.25, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

So, by default, `cut` produces labels that indicate the bin boundaries for each element in the series it was applied to. Usually, we will specify labels that are appropriate to the discretisation we are applying:

In [11]:
atemp_level = pd.cut(bikes['atemp'], bins = 4, labels = ["cool", "mild", "warm", "hot"])
atemp_level

0        mild
1        mild
2        mild
3        mild
4        mild
         ...
17374    mild
17375    mild
17376    mild
17377    mild
17378    mild
Name: atemp, Length: 17379, dtype: category
Categories (4, object): ['cool' < 'mild' < 'warm' < 'hot']

Incorporate the new `atemp_level` column into the `bikes` DataFrame and use it to count the number of "mild" `atemp` entries in `season` 2:

In [12]:
bikes['atemp_level']= atemp_level

bikes[(bikes.atemp_level == 'mild') & (bikes.season == 2)].season.count()

1829

In [ ]:
bikes.to_csv("data.csv")

*Nb. The `atemp_level` variable we created is what the R language calls a "factor". Pandas has introduced a new data type called "category" that is similar to R's factors.*

# Synthetic Data

Sometimes we may want to generate test data, or we may need to initalise a series, matrix, or data frame for input to an algorithm. Numpy has several methods we can use for this.

Execute the following, then check the shape and content of each variable:

In [19]:
# Creating arrays with initial values
import numpy as np
a = np.zeros((3))
b = np.ones((1,3))
c = np.random.randint(1,10,(2,3,10))   # randint(low, high, size)
d = np.arange(4)
e = np.array( [[1,2,3,4], [5,6,7,8]] )
print('This is a:', a)
print('This is b:',b)
print('This is c:',c)
print('This is d:',d)
print('This is e:',e)

This is a: [0. 0. 0.]
This is b: [[1. 1. 1.]]
This is c: [[[7 7 3 7 8 5 7 1 6 8]
  [3 9 6 9 8 2 4 5 5 3]
  [2 7 5 6 1 7 9 7 4 6]]

 [[1 1 9 9 4 4 2 3 6 2]
  [1 5 8 4 4 4 3 3 7 9]
  [1 6 1 1 6 3 6 3 1 6]]]
This is d: [0 1 2 3]
This is e: [[1 2 3 4]
 [5 6 7 8]]

## Load Data

Load rock.csv and clean the dataset.

In [45]:
# ANSWER
import pandas as pd
rock_csv= r"C:\Users\preej\IOD\Workspace\Module 2 --- Week2\rock.csv"
rock = pd.read_csv(rock_csv)
rock.columns
rock

,Song Clean,ARTIST CLEAN,Release Year,COMBINED,First?,Year?,PlayCount,F*G
0,Caught Up in You,.38 Special,1982,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,NaN,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975,Art For Arts Sake by 10cc,1,1,1,1
...,...,...,...,...,...,...,...,...
2225,She Loves My Automobile,ZZ Top,NaN,She Loves My Automobile by ZZ Top,1,0,1,0
2226,Tube Snake Boogie,ZZ Top,1981,Tube Snake Boogie by ZZ Top,1,1,32,32
2227,Tush,ZZ Top,1975,Tush by ZZ Top,1,1,109,109
2228,TV Dinners,ZZ Top,1983,TV Dinners by ZZ Top,1,1,1,1
2229,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO,ZZ Top,1973,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...,1,1,2,2

## Check Column Names

Check column names and clean.

In [46]:
# ANSWER

import pandas as pd

df=pd.DataFrame(rock)

# Clean column names by replacing '?' and '*' with underscores
rock.columns = rock.columns.str.replace('[?* ]','.').str.lower()

print("Current column names:")
print(df.columns)

Current column names:
Index(['song.clean', 'artist.clean', 'release.year', 'combined', 'first.',
       'year.', 'playcount', 'f.g'],
      dtype='object')

C:\Users\preej\AppData\Local\Temp\ipykernel_13120\3092163296.py:8: FutureWarning: The default value of regex will change from True to False in a future version.
  rock.columns = rock.columns.str.replace('[?* ]','.').str.lower()

## Replace Null Values With 0

Check 'release' column whether this column have any null value or not. Replace null value with 0.

In [47]:
# ANSWER
df['release.year'].isnull()

df['release.year'].fillna(0,inplace=True)
df['release.year']

0       1982
1          0
2       1981
3       1980
4       1975
        ...
2225       0
2226    1981
2227    1975
2228    1983
2229    1973
Name: release.year, Length: 2230, dtype: object

## Check Datatypes of Dataset

Check datatypes of the dataset. Is there any column which should be int instead of object? Fix the column.

In [48]:
import pandas as pd

# Convert 'release' column to integer

df['release.year'] = pd.to_numeric(df['release.year'], errors='coerce').astype('Int64')


print(df.dtypes)

song.clean      object
artist.clean    object
release.year     Int64
combined        object
first.           int64
year.            int64
playcount        int64
f.g              int64
dtype: object

## Check Min, Max of Each Column

Is there any illogical value in any column? How can we fix that?

In [49]:
# ANSWER

def check_min_max(df):
    # Check min, max of each column
    print(df.describe().T[['min', 'max']])
    
check_min_max(df)
rock[0:1]
rock

              min     max
release.year  0.0  2014.0
first.        1.0     1.0
year.         0.0     1.0
playcount     0.0   142.0
f.g           0.0   142.0

,song.clean,artist.clean,release.year,combined,first.,year.,playcount,f.g
0,Caught Up in You,.38 Special,1982,Caught Up in You by .38 Special,1,1,82,82
1,Fantasy Girl,.38 Special,0,Fantasy Girl by .38 Special,1,0,3,0
2,Hold On Loosely,.38 Special,1981,Hold On Loosely by .38 Special,1,1,85,85
3,Rockin' Into the Night,.38 Special,1980,Rockin' Into the Night by .38 Special,1,1,18,18
4,Art For Arts Sake,10cc,1975,Art For Arts Sake by 10cc,1,1,1,1
...,...,...,...,...,...,...,...,...
2225,She Loves My Automobile,ZZ Top,0,She Loves My Automobile by ZZ Top,1,0,1,0
2226,Tube Snake Boogie,ZZ Top,1981,Tube Snake Boogie by ZZ Top,1,1,32,32
2227,Tush,ZZ Top,1975,Tush by ZZ Top,1,1,109,109
2228,TV Dinners,ZZ Top,1983,TV Dinners by ZZ Top,1,1,1,1
2229,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO,ZZ Top,1973,WAITIN' FOR THE BUS/JESUS JUST LEFT CHICAGO by...,1,1,2,2

## Write Some Functions

### Write a function that will take a row of a DataFrame and print out the song, artist, and whether or not the release date is < 1970

In [40]:
def print_song_artist_release(row):
    song_name = row['song.clean']
    artist_name = row['artist.clean']
    release_year = row['release.year']

    print(f"Song: {song_name}")
    print(f"Artist: {artist_name}")

    # Convert release_year to an integer before comparison
    release_year = int(release_year)

    if release_year < 1970:
        print("Release Date: Before 1970")
    else:
        print("Release Date: After 1970")

# Example usage:
# Assuming 'df' is the DataFrame containing the data
# Let's say we want to print information for the first row (index 0):
print_song_artist_release(df.iloc[0])

Song: <NA>
Artist: <NA>
Release Date: After 1970

In [52]:
import pandas as pd

def print_songs_before_1970(df):
    # Convert 'release.year' to numeric data, coercing non-convertible values to NaN
    df['release.year'] = pd.to_numeric(df['release.year'], errors='coerce')
    
    # Filter the DataFrame and drop rows with NaN values in 'release.year'
    filtered_df = df[df['release.year'] < 1970].dropna(subset=['release.year'])
  
    
    for index, row in filtered_df.iterrows():
        print(f"Song: {row['song.clean']}")
        print(f"Artist: {row['artist.clean']}")
        print(f"Release Year: {int(row['release.year'])}")
        print("---")

# Assuming 'df' is the DataFrame containing the data
print_songs_before_1970(df)

Song: Fantasy Girl
Artist: .38 Special
Release Year: 0
---
Song: Baby, Please Don't Go
Artist: AC/DC
Release Year: 0
---
Song: CAN'T STOP ROCK'N'ROLL
Artist: AC/DC
Release Year: 0
---
Song: Girls Got Rhythm
Artist: AC/DC
Release Year: 0
---
Song: Let's Get It Up
Artist: AC/DC
Release Year: 0
---
Song: Live Wire
Artist: AC/DC
Release Year: 0
---
Song: Moneytalks
Artist: AC/DC
Release Year: 0
---
Song: Shoot To Thrill
Artist: AC/DC
Release Year: 0
---
Song: Sin City
Artist: AC/DC
Release Year: 0
---
Song: What Do You Do For Money Honey
Artist: AC/DC
Release Year: 0
---
Song: Baby, Please Don't Go
Artist: Aerosmith
Release Year: 0
---
Song: Come Together
Artist: Aerosmith
Release Year: 0
---
Song: Kings and Queens
Artist: Aerosmith
Release Year: 0
---
Song: One Way Street
Artist: Aerosmith
Release Year: 0
---
Song: The Other Side
Artist: Aerosmith
Release Year: 0
---
Song: You See Me Crying
Artist: Aerosmith
Release Year: 0
---
Song: Fantasy
Artist: Aldo Nova
Release Year: 0
---
Song: BE MY LOVER
Artist: Alice Cooper
Release Year: 0
---
Song: House Of Fire
Artist: Alice Cooper
Release Year: 0
---
Song: One Way Out
Artist: Allman Brothers Band
Release Year: 0
---
Song: Southbound
Artist: Allman Brothers Band
Release Year: 0
---
Song: Whippin' Post
Artist: Allman Brothers Band
Release Year: 0
---
Song: Don't Bring Me Down
Artist: Animals II
Release Year: 1966
---
Song: Don't Let Me Be Misunderstood
Artist: Animals II
Release Year: 1965
---
Song: Immigrant Song
Artist: Ann Wilson
Release Year: 0
---
Song: Roller
Artist: April Wine
Release Year: 0
---
Song: Coming into Los Angeles
Artist: Arlo Guthrie
Release Year: 0
---
Song: Wayside
Artist: Artful Dodger
Release Year: 0
---
Song: Spooky
Artist: Atlanta Rhythm Section
Release Year: 0
---
Song: Blondes In Black Cars
Artist: Autograph
Release Year: 0
---
Song: Rock And Roll Party In The Streets
Artist: Axe
Release Year: 0
---
Song: Roll On Down The Highway
Artist: Bachman-Turner Overdrive
Release Year: 0
---
Song: Feel Like Makin' Love
Artist: Bad Company
Release Year: 0
---
Song: Gone Gone Gone
Artist: Bad Company
Release Year: 0
---
Song: Good Lovin' Gone Bad
Artist: Bad Company
Release Year: 0
---
Song: Movin' On
Artist: Bad Company
Release Year: 0
---
Song: Ready For Love
Artist: Bad Company
Release Year: 0
---
Song: Rock 'n' Roll Fantasy
Artist: Bad Company
Release Year: 0
---
Song: Rock Steady
Artist: Bad Company
Release Year: 0
---
Song: Run With The Pack
Artist: Bad Company
Release Year: 0
---
Song: Silver, Blue And Gold
Artist: Bad Company
Release Year: 0
---
Song: Walks Like A Woman
Artist: Baton Rouge
Release Year: 0
---
Song: Rock Around the Clock
Artist: Bill Haley
Release Year: 1955
---
Song: Mony Mony
Artist: Billy Idol
Release Year: 0
---
Song: Don't Ask Me Why
Artist: Billy Joel
Release Year: 0
---
Song: Prelude/angry Young Man
Artist: Billy Joel
Release Year: 0
---
Song: Baby Come Back
Artist: Billy Rankin
Release Year: 0
---
Song: Everybody Wants You
Artist: Billy Squier
Release Year: 0
---
Song: In the Dark
Artist: Billy Squier
Release Year: 0
---
Song: My Kinda Lover
Artist: Billy Squier
Release Year: 0
---
Song: She's a Runner
Artist: Billy Squier
Release Year: 0
---
Song: Children Of The Sun
Artist: Billy Thorpe
Release Year: 0
---
Song: Highway Song
Artist: Blackfoot
Release Year: 0
---
Song: Can't Find My Way Home
Artist: Blind Faith
Release Year: 1969
---
Song: Presence of the Lord
Artist: Blind Faith
Release Year: 1969
---
Song: Presence of the Lord
Artist: Blind Melon
Release Year: 0
---
Song: Bucks Boogie
Artist: Blue Oyster Cult
Release Year: 0
---
Song: Summertime Blues
Artist: Blue Oyster Cult
Release Year: 0
---
Song: Just Like A Woman
Artist: Bob Dylan
Release Year: 1966
---
Song: Like a Rolling Stone
Artist: Bob Dylan
Release Year: 1965
---
Song: Positively 4th Street
Artist: Bob Dylan
Release Year: 1965
---
Song: Subterranean Homesick Blues
Artist: Bob Dylan
Release Year: 1965
---
Song: Exodus
Artist: Bob Marley
Release Year: 0
---
Song: Jamming
Artist: Bob Marley
Release Year: 0
---
Song: Stir It Up
Artist: Bob Marley
Release Year: 0
---
Song: Three Little Birds
Artist: Bob Marley
Release Year: 0
---
Song: Betty Lou's Gettin' Out Tonigh
Artist: Bob Seger
Release Year: 0
---
Song: Come to Poppa
Artist: Bob Seger
Release Year: 0
---
Song: Feel Like a Number
Artist: Bob Seger
Release Year: 0
---
Song: Get Out of Denver
Artist: Bob Seger
Release Year: 0
---
Song: Horizontal Bop
Artist: Bob Seger
Release Year: 0
---
Song: Ramblin' Gamblin' Man
Artist: Bob Seger
Release Year: 1968
---
Song: Roll Me Away
Artist: Bob Seger
Release Year: 0
---
Song: Sunspot Baby
Artist: Bob Seger
Release Year: 0
---
Song: The Fire Down Below
Artist: Bob Seger
Release Year: 0
---
Song: Travelin' Man
Artist: Bob Seger
Release Year: 0
---
Song: Turn On Your Love Light
Artist: Bob Seger
Release Year: 0
---
Song: You'll Accompany Me
Artist: Bob Seger
Release Year: 0
---
Song: Hypnotized
Artist: Bob Welch
Release Year: 0
---
Song: Raise Your Hands
Artist: Bon Jovi
Release Year: 0
---
Song: She Don't Know Me
Artist: Bon Jovi
Release Year: 0
---
Song: Wait For You
Artist: Bonham
Release Year: 0
---
Song: Green Onions
Artist: Booker T. and the MG's
Release Year: 1962
---
Song: A Man I'll Never Be
Artist: Boston
Release Year: 0
---
Song: Cool The Engines
Artist: Boston
Release Year: 0
---
Song: Feelin' Satisfied
Artist: Boston
Release Year: 0
---
Song: Party
Artist: Boston
Release Year: 0
---
Song: Something About You
Artist: Boston
Release Year: 0
---
Song: The Journey/It's Easy
Artist: Boston
Release Year: 0
---
Song: Used To Bad News
Artist: Boston
Release Year: 0
---
Song: We're Ready
Artist: Boston
Release Year: 0
---
Song: Tarkio Road
Artist: Brewer & Shipley
Release Year: 0
---
Song: Jersey Girl
Artist: Bruce Springsteen
Release Year: 0
---
Song: For What It's Worth
Artist: Buffalo Springfield
Release Year: 1966
---
Song: Mr. Soul
Artist: Buffalo Springfield
Release Year: 1967
---
Song: Rock & Roll Woman
Artist: Buffalo Springfield
Release Year: 0
---
Song: Goin' up the Country
Artist: Canned Heat
Release Year: 1968
---
Song: On the Road Again
Artist: Canned Heat
Release Year: 1968
---
Song: Oh Very Young
Artist: Cat Stevens
Release Year: 0
---
Song: The Legend Of Wooley Swamp
Artist: Charlie Daniels Band
Release Year: 0
---
Song: Ain't That a Shame
Artist: Cheap Trick
Release Year: 0
---
Song: Dream Police
Artist: Cheap Trick
Release Year: 0
---
Song: She's Tight
Artist: Cheap Trick
Release Year: 0
---
Song: Beginnings
Artist: Chicago
Release Year: 0
---
Song: I'm a Man
Artist: Chicago
Release Year: 0
---
Song: JUST YOU AND ME
Artist: Chicago
Release Year: 0
---
Song: Questions 67 and 68
Artist: Chicago
Release Year: 1969
---
Song: South California Purples
Artist: Chicago
Release Year: 0
---
Song: JOHNNY B. GOODE
Artist: Chuck Berry
Release Year: 1958
---
Song: Better Off Without You
Artist: Clarks
Release Year: 0
---
Song: Born Too Late
Artist: Clarks
Release Year: 0
---
Song: Cigarette
Artist: Clarks
Release Year: 0
---
Song: Hey You
Artist: Clarks
Release Year: 0
---
Song: Maybe
Artist: Clarks
Release Year: 0
---
Song: Penny On The Floor
Artist: Clarks
Release Year: 0
---
Song: The River
Artist: Clarks
Release Year: 0
---
Song: December
Artist: Collective Soul
Release Year: 0
---
Song: Monkey Bars
Artist: Coney Hatch
Release Year: 0
---
Song: Badge
Artist: Cream
Release Year: 1969
---
Song: Born Under A Bad Sign
Artist: Cream
Release Year: 0
---
Song: Crossroads
Artist: Cream
Release Year: 1968
---
Song: I'm So Glad
Artist: Cream
Release Year: 1966
---
Song: Sunshine of Your Love
Artist: Cream
Release Year: 1967
---
Song: Tales Of Brave Ulysses
Artist: Cream
Release Year: 1967
---
Song: White Room
Artist: Cream
Release Year: 1968
---
Song: My Sacrifice
Artist: Creed
Release Year: 0
---
Song: Bad Moon Rising
Artist: Creedence Clearwater Revival
Release Year: 1969
---
Song: Born On the Bayou
Artist: Creedence Clearwater Revival
Release Year: 1969
---
Song: Commotion
Artist: Creedence Clearwater Revival
Release Year: 0
---
Song: Down On the Corner
Artist: Creedence Clearwater Revival
Release Year: 1969
---
Song: Green River
Artist: Creedence Clearwater Revival
Release Year: 1969
---
Song: I Heard It Through the Grapevine
Artist: Creedence Clearwater Revival
Release Year: 0
---
Song: Lodi
Artist: Creedence Clearwater Revival
Release Year: 1969
---
Song: Proud Mary
Artist: Creedence Clearwater Revival
Release Year: 1969
---
Song: Suzie Q
Artist: Creedence Clearwater Revival
Release Year: 1968
---
Song: The Midnight Special
Artist: Creedence Clearwater Revival
Release Year: 0
---
Song: Fire Woman
Artist: Crosby, Stills & Nash
Release Year: 0
---
Song: Helplessly Hoping
Artist: Crosby, Stills & Nash
Release Year: 1969
---
Song: Long Time Gone
Artist: Crosby, Stills & Nash
Release Year: 1969
---
Song: Suite: Judy Blue Eyes
Artist: Crosby, Stills & Nash
Release Year: 1969
---
Song: Headkeeper
Artist: Dave Mason
Release Year: 0
---
Song: Only You Know And I Know
Artist: Dave Mason
Release Year: 0
---
Song: Friday on My Mind
Artist: David Bowie
Release Year: 0
---
Song: Jean Genie
Artist: David Bowie
Release Year: 0
---
Song: Panic in Detroit
Artist: David Bowie
Release Year: 0
---
Song: Space Oddity
Artist: David Bowie
Release Year: 1969
---
Song: Stay
Artist: David Bowie
Release Year: 0
---
Song: There's No Way Out Of Here
Artist: David Essex
Release Year: 0
---
Song: There's No Way Out Of Here
Artist: David Gilmour
Release Year: 0
---
Song: Frenchette
Artist: David Johansen
Release Year: 0
---
Song: California Girls
Artist: David Lee Roth
Release Year: 0
---
Song: Hush
Artist: Deep Purple
Release Year: 1968
---
Song: Kentucky Woman
Artist: Deep Purple
Release Year: 1968
---
Song: Perfect Strangers
Artist: Deep Purple
Release Year: 0
---
Song: Space Truckin'
Artist: Deep Purple
Release Year: 0
---
Song: Woman From Tokyo
Artist: Deep Purple
Release Year: 0
---
Song: Bringin' On The Heartbreak
Artist: Def Leppard
Release Year: 0
---
Song: Foolin'
Artist: Def Leppard
Release Year: 0
---
Song: On Through The Night
Artist: Def Leppard
Release Year: 0
---
Song: Rock Rock
Artist: Def Leppard
Release Year: 0
---
Song: Too Late for Love
Artist: Def Leppard
Release Year: 0
---
Song: Have You Ever Loved a Woman
Artist: Derek & The Dominos
Release Year: 0
---
Song: Recognition
Artist: Detective
Release Year: 0
---
Song: ANGELOS
Artist: Dick Siegel
Release Year: 0
---
Song: Holy Diver
Artist: Dio
Release Year: 0
---
Song: Rainbow In the Dark
Artist: Dio
Release Year: 0
---
Song: The Last In Line
Artist: Dio
Release Year: 0
---
Song: Solid Rock
Artist: Dire Straits
Release Year: 0
---
Song: Alone Again
Artist: Dokken
Release Year: 0
---
Song: In My Dreams
Artist: Dokken
Release Year: 0
---
Song: Into The Fire
Artist: Dokken
Release Year: 0
---
Song: The Last Worthless Evening
Artist: Don Henley
Release Year: 0
---
Song: Season of the Witch
Artist: Donovan
Release Year: 1966
---
Song: Sunshine Superman
Artist: Donovan
Release Year: 1966
---
Song: COVER OF THE ROLLING STONE
Artist: Dr. Hook & the Medicine Show
Release Year: 0
---
Song: Anything, Anything
Artist: Dramarama
Release Year: 0
---
Song: Gimme Some Water
Artist: Eddie Money
Release Year: 0
---
Song: Shakin'
Artist: Eddie Money
Release Year: 0
---
Song: Think I'm In Love
Artist: Eddie Money
Release Year: 0
---
Song: Two Tickets To Paradise
Artist: Eddie Money
Release Year: 0
---
Song: Frankenstein
Artist: Edgar Winter Group
Release Year: 0
---
Song: Do Ya
Artist: Electric Light Orchestra
Release Year: 0
---
Song: Roll Over Beethoven
Artist: Electric Light Orchestra
Release Year: 0
---
Song: Telephone Line
Artist: Electric Light Orchestra
Release Year: 0
---
Song: Levon
Artist: Elton John
Release Year: 1071
---
Song: Take Me to the Pilot
Artist: Elton John
Release Year: 0
---
Song: Teacher I Need You
Artist: Elton John
Release Year: 0
---
Song: Hoedown
Artist: Emerson, Lake & Palmer
Release Year: 0
---
Song: Call Me the Breeze
Artist: Eric Clapton
Release Year: 0
---
Song: Don't Think Twice, It's Alright
Artist: Eric Clapton
Release Year: 0
---
Song: I've Got a Rock 'N' Roll Heart
Artist: Eric Clapton
Release Year: 0
---
Song: Knockin' On Heaven's Door
Artist: Eric Clapton
Release Year: 0
---
Song: Layla
Artist: Eric Clapton
Release Year: 0
---
Song: Tears In Heaven
Artist: Eric Clapton
Release Year: 0
---
Song: Willie and the Hand Jive
Artist: Eric Clapton
Release Year: 0
---
Song: Inside Out
Artist: Eve 6
Release Year: 0
---
Song: The Boys Are Back In Town
Artist: Everclear
Release Year: 0
---
Song: Mutha (Don't Wanna Go To School Today)
Artist: Extreme
Release Year: 0
---
Song: All The Kings Horses
Artist: Firm
Release Year: 0
---
Song: Blue Letter
Artist: Fleetwood Mac
Release Year: 0
---
Song: I'm So Afraid
Artist: Fleetwood Mac
Release Year: 0
---
Song: Oh Well
Artist: Fleetwood Mac
Release Year: 1969
---
Song: Say You Love Me
Artist: Fleetwood Mac
Release Year: 0
---
Song: Sentimental Lady
Artist: Fleetwood Mac
Release Year: 0
---
Song: World Turning
Artist: Fleetwood Mac
Release Year: 0
---
Song: Dreamer
Artist: Foghat
Release Year: 0
---
Song: I Just Want To Make Love To You
Artist: Foghat
Release Year: 0
---
Song: Baker Street
Artist: Foo Fighters
Release Year: 0
---
Song: Blue Morning, Blue Day
Artist: Foreigner
Release Year: 0
---
Song: Head Games
Artist: Foreigner
Release Year: 0
---
Song: Long, Long Way From Home
Artist: Foreigner
Release Year: 0
---
Song: Love Has Taken Its Toll
Artist: Foreigner
Release Year: 0
---
Song: Starrider
Artist: Foreigner
Release Year: 0
---
Song: Women
Artist: Foreigner
Release Year: 0
---
Song: Peaches En Regalia
Artist: Frank Zappa
Release Year: 0
---
Song: Hemorrhage
Artist: Free
Release Year: 0
---
Song: Love Is Alive
Artist: Gary Wright
Release Year: 0
---
Song: Behind The Lines
Artist: Genesis
Release Year: 0
---
Song: Carpet Crawlers
Artist: Genesis
Release Year: 0
---
Song: Just A Job To Do
Artist: Genesis
Release Year: 0
---
Song: Delaware Slide
Artist: George Thorogood
Release Year: 0
---
Song: Get A Haircut
Artist: George Thorogood
Release Year: 0
---
Song: It Wasn't Me
Artist: George Thorogood
Release Year: 0
---
Song: Move It On Over
Artist: George Thorogood
Release Year: 0
---
Song: One Bourbon, One Scotch, One Beer
Artist: George Thorogood
Release Year: 0
---
Song: Who Do You Love
Artist: George Thorogood
Release Year: 0
---
Song: Marakesh Express
Artist: Gold Star Ballroom Orchestra
Release Year: 0
---
Song: Soulshine
Artist: Gov't Mule
Release Year: 0
---
Song: Alabama Getaway
Artist: Grateful Dead
Release Year: 0
---
Song: Black-Throated Wind
Artist: Grateful Dead
Release Year: 0
---
Song: CHINA TOWN SHUFFLE
Artist: Grateful Dead
Release Year: 0
---
Song: Hell in a Bucket
Artist: Grateful Dead
Release Year: 0
---
Song: Loser
Artist: Grateful Dead
Release Year: 0
---
Song: Me and Bobby McGee
Artist: Grateful Dead
Release Year: 0
---
Song: NOT FADEAWAY/GOING /AWAY
Artist: Grateful Dead
Release Year: 0
---
Song: Scarlet Begonias
Artist: Grateful Dead
Release Year: 0
---
Song: Shakedown Street
Artist: Grateful Dead
Release Year: 0
---
Song: Turn On Your Lovelight
Artist: Grateful Dead
Release Year: 0
---
Song: U.S. Blues
Artist: Grateful Dead
Release Year: 0
---
Song: Uncle John's Band
Artist: Grateful Dead
Release Year: 1969
---
Song: Mista Bone
Artist: Great White
Release Year: 0
---
Song: Rock Me
Artist: Great White
Release Year: 0
---
Song: Rollin' Stoned
Artist: Great White
Release Year: 0
---
Song: Save Your Love
Artist: Great White
Release Year: 0
---
Song: Friends Of Mine
Artist: Guess Who
Release Year: 0
---
Song: No Time
Artist: Guess Who
Release Year: 0
---
Song: THESE EYES
Artist: Guess Who
Release Year: 1969
---
Song: Don't Cry
Artist: Guns N' Roses
Release Year: 0
---
Song: Knockin' On Heaven's Door
Artist: Guns N' Roses
Release Year: 0
---
Song: Live and Let Die
Artist: Guns N' Roses
Release Year: 0
---
Song: You Could Be Mine
Artist: Guns N' Roses
Release Year: 0
---
Song: AS FAR AS YOU CAN SEE (AS MU
Artist: Gypsy
Release Year: 0
---
Song: Jump into the Fire
Artist: Harry Nilsson
Release Year: 0
---
Song: All I Wanna Do Is Make Love to You
Artist: Heart
Release Year: 0
---
Song: Bebe le Strange
Artist: Heart
Release Year: 0
---
Song: Dog & Butterfly
Artist: Heart
Release Year: 0
---
Song: Even It Up
Artist: Heart
Release Year: 0
---
Song: Heartless
Artist: Heart
Release Year: 0
---
Song: If Looks Could Kill
Artist: Heart
Release Year: 0
---
Song: Kick It Out
Artist: Heart
Release Year: 0
---
Song: Little Queen
Artist: Heart
Release Year: 0
---
Song: Love Alive
Artist: Heart
Release Year: 0
---
Song: Mistral Wind
Artist: Heart
Release Year: 0
---
Song: Never
Artist: Heart
Release Year: 0
---
Song: Nothin' at All
Artist: Heart
Release Year: 0
---
Song: Rock And Roll
Artist: Heart
Release Year: 0
---
Song: Stairway To Heaven
Artist: Heart
Release Year: 0
---
Song: Tell It Like It Is
Artist: Heart
Release Year: 0
---
Song: What About Love?
Artist: Heart
Release Year: 0
---
Song: Who Will You Run To
Artist: Heart
Release Year: 0
---
Song: House Of Living
Artist: Heartsfield
Release Year: 0
---
Song: Sangre Por Sangre
Artist: HellYeah
Release Year: 0
---
Song: New Girl Now
Artist: Honeymoon Suite
Release Year: 0
---
Song: New Sensation
Artist: INXS
Release Year: 0
---
Song: In A Gadda Da Vida
Artist: Iron Butterfly
Release Year: 1968
---
Song: Houseparty
Artist: J. Geils Band
Release Year: 0
---
Song: Looking For A Love
Artist: J. Geils Band
Release Year: 0
---
Song: Love Stinks
Artist: J. Geils Band
Release Year: 0
---
Song: Must of Got Lost
Artist: J. Geils Band
Release Year: 0
---
Song: Night Time
Artist: J. Geils Band
Release Year: 0
---
Song: Whammer Jammer
Artist: J. Geils Band
Release Year: 0
---
Song: Boulevard
Artist: Jackson Browne
Release Year: 0
---
Song: Take It Easy
Artist: Jackson Browne
Release Year: 0
---
Song: Walk Away
Artist: James Gang
Release Year: 0
---
Song: Piece of My Heart
Artist: Janis Joplin
Release Year: 1968
---
Song: Summertime
Artist: Janis Joplin
Release Year: 0
---
Song: Shakedown Cruise
Artist: Jay Ferguson
Release Year: 0
---
Song: Rice Pudding
Artist: Jeff Beck
Release Year: 0
---
Song: Somebody to Love
Artist: Jefferson Airplane
Release Year: 1967
---
Song: White Rabbit
Artist: Jefferson Airplane
Release Year: 1967
---
Song: Find Your Way Back
Artist: Jefferson Starship
Release Year: 0
---
Song: Ride the Tiger
Artist: Jefferson Starship
Release Year: 0
---
Song: Hymn 43
Artist: Jethro Tull
Release Year: 0
---
Song: Living In The Past
Artist: Jethro Tull
Release Year: 1969
---
Song: Nothing Is Easy
Artist: Jethro Tull
Release Year: 0
---
Song: Thick As A Brick
Artist: Jethro Tull
Release Year: 0
---
Song: Too Old To Rock 'n' Roll
Artist: Jethro Tull
Release Year: 0
---
Song: All Along the Watchtower
Artist: Jimi Hendrix
Release Year: 1968
---
Song: Are You Experienced?
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Crosstown Traffic
Artist: Jimi Hendrix
Release Year: 1968
---
Song: Fire
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Foxey Lady
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Hey Joe
Artist: Jimi Hendrix
Release Year: 1966
---
Song: If 6 Was 9
Artist: Jimi Hendrix
Release Year: 0
---
Song: Like a Rolling Stone
Artist: Jimi Hendrix
Release Year: 0
---
Song: Little Wing
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Manic Depression
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Purple Haze
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Red House
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Stone Free
Artist: Jimi Hendrix
Release Year: 1966
---
Song: The Wind Cries Mary
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Third Stone From The Sun
Artist: Jimi Hendrix
Release Year: 1967
---
Song: Voodoo Child (Slight Return)
Artist: Jimi Hendrix
Release Year: 1968
---
Song: Crimson And Clover
Artist: Joan Jett
Release Year: 0
---
Song: Cry Me a River
Artist: Joe Cocker
Release Year: 0
---
Song: Feelin' Alright
Artist: Joe Cocker
Release Year: 0
---
Song: The Letter
Artist: Joe Cocker

### Write a function that converts cells in a DataFrame to float and otherwise replaces them with np.nan

In [41]:
# ANSWER
import pandas as pd
import numpy as np

def convert_to_float(df):
    def try_convert_to_float(value):
        try:
            return float(value)
        except (ValueError, TypeError):
            return np.nan

    return df.applymap(try_convert_to_float)

df = convert_to_float(df)

### Apply these functions to your dataset

In [53]:
# ANSWER
import pandas as pd
import numpy as np

# Applying the convert_to_float function to the DataFrame
df = convert_to_float(df)

# Printing the updated DataFrame
print(df)

      song.clean  artist.clean  release.year  combined  first.  year.  \
0            NaN           NaN        1982.0       NaN     1.0    1.0
1            NaN           NaN           0.0       NaN     1.0    0.0
2            NaN           NaN        1981.0       NaN     1.0    1.0
3            NaN           NaN        1980.0       NaN     1.0    1.0
4            NaN           NaN        1975.0       NaN     1.0    1.0
...          ...           ...           ...       ...     ...    ...
2225         NaN           NaN           0.0       NaN     1.0    0.0
2226         NaN           NaN        1981.0       NaN     1.0    1.0
2227         NaN           NaN        1975.0       NaN     1.0    1.0
2228         NaN           NaN        1983.0       NaN     1.0    1.0
2229         NaN           NaN        1973.0       NaN     1.0    1.0

      playcount    f.g
0          82.0   82.0
1           3.0    0.0
2          85.0   85.0
3          18.0   18.0
4           1.0    1.0
...         ...    ...
2225        1.0    0.0
2226       32.0   32.0
2227      109.0  109.0
2228        1.0    1.0
2229        2.0    2.0

[2230 rows x 8 columns]

### Describe the new float-only DataFrame.

In [ ]:
# ANSWER
The entire DataFrame converted to float, columns that were originally string-based or
binary will now contain NaN values entirely.
Only columns with numeric data (e.g., 'release.year', 'playcount', and 'f.g') will retain
their numeric values after the conversion.

>



---



---



> > > > > > > > > © 2023 Institute of Data


---



---